# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 10:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0002_auto_20160508_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CiscoApiAuthSettings',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='product',
            name='end_of_sec_vuln_supp_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Vulnerability/Security Support date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US-Dollar')], default='USD', help_text='currency of the list price', max_length=16, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='not set', help_text='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_new_service_attachment_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of New Service Attachment Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_routine_failure_analysis',
            field=models.DateField(blank=True, null=True, verbose_name='End of Routine Failure Analysis Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='End-of-Sale Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_service_contract_renewal',
            field=models.DateField(blank=True, null=True, verbose_name='End of Service Contract Renewal Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_support_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Date of Support'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_sw_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of SW Maintenance Releases Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eol_ext_announcement_date',
            field=models.DateField(blank=True, null=True, verbose_name='End-of-Life Announcement Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eol_reference_number',
            field=models.TextField(blank=True, help_text='Product bulletin number or vendor specific reference for EoL', null=True, verbose_name='EoL reference number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eol_reference_url',
            field=models.URLField(blank=True, help_text='URL to the Product bulletin or EoL reference', null=True, verbose_name='EoL reference URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eox_update_time_stamp',
            field=models.DateField(blank=True, null=True, verbose_name='EoX lifecycle data timestamp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='list price of the element', max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='list price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Unique Product ID/Number', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='unformatted tag field', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='productdb.Vendor', verbose_name='Vendor'),
        ),
    ]
