# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0004_jobfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eol_reference_number',
            field=models.CharField(blank=True, help_text='Product bulletin number or vendor specific reference for EoL', max_length=2048, null=True, verbose_name='EoL reference number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='eox_update_time_stamp',
            field=models.DateField(blank=True, help_text='Indicates that the product has lifecycle data and when they were last updated. If no EoL announcement date is set, the product is considered as not EoL/EoS.', null=True, verbose_name='EoX lifecycle data timestamp'),
        ),
    ]
