# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0006_auto_20160702_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Product Group', max_length=512)),
                ('vendor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='productdb.Vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productdb.ProductGroup', verbose_name='Product Group'),
        ),
        migrations.AlterUniqueTogether(
            name='productgroup',
            unique_together=set([('name', 'vendor')]),
        ),
    ]
