# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0008_auto_20160717_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_id',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'product group', 'verbose_name_plural': 'product groups'},
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('name',), 'verbose_name': 'product list', 'verbose_name_plural': 'product lists'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',), 'verbose_name': 'vendor', 'verbose_name_plural': 'vendors'},
        ),
    ]
