# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='regex_search',
            field=models.BooleanField(default=True, help_text='Use regular expression in any search field (fallback to simple search if no valid regular expression is used)', verbose_name='use regex search'),
            preserve_default=False,
        ),
    ]
