# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 18:57
from __future__ import unicode_literals

import app.productdb.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0012_auto_20160725_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='description',
            field=models.TextField(blank=True, help_text="short description what's part of this Product List", max_length=4096, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='name',
            field=models.CharField(help_text='unique name for the product list', max_length=2048, unique=True, verbose_name='Product List Name'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='string_product_list',
            field=models.TextField(help_text='Product IDs separated by word wrap or semicolon', max_length=16384, validators=[app.productdb.validators.validate_product_list_string], verbose_name='Unstructured Product ID list'),
        ),
    ]
