# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0013_auto_20160907_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.FloatField(blank=True, help_text='list price of the element', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='list price'),
        ),
    ]
