# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0014_auto_20160912_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lc_state_sync',
            field=models.BooleanField(default=False, help_text='product is automatically synchronized against the vendor data', verbose_name='lifecycle data automatically synchronized'),
        ),
    ]
