# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0015_product_lc_state_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_product_id',
            field=models.CharField(blank=True, help_text='optional internal reference for the Product', max_length=255, null=True, verbose_name='Internal Product ID'),
        ),
    ]
