# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0016_product_internal_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMigrationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_product_id', models.CharField(blank=True, help_text='the suggested replacement option', max_length=512)),
                ('comment', models.TextField(blank=True, help_text='comment from the group (optional)', max_length=4096)),
                ('migration_product_info_url', models.URLField(blank=True, help_text='Migration Product Information URL', null=True, verbose_name='Migration Product Info URL')),
            ],
            options={
                'verbose_name_plural': 'product migration options',
                'verbose_name': 'product migration option',
                'ordering': ['-migration_source__preference'],
            },
        ),
        migrations.CreateModel(
            name='ProductMigrationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the migration source', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('preference', models.PositiveSmallIntegerField(default=50, help_text='preference value, identifies which source is preferred over another (100 is most preferred)', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'product migration sources',
                'verbose_name': 'product migration source',
                'ordering': ['-preference', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productmigrationoption',
            name='migration_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productdb.ProductMigrationSource'),
        ),
        migrations.AddField(
            model_name='productmigrationoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productdb.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='productmigrationoption',
            unique_together=set([('product', 'migration_source')]),
        ),
    ]
