# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-30 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0017_auto_20161027_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='version_note',
            field=models.TextField(blank=True, help_text='some version information for the product list (markdown formatting supported)', max_length=16384, verbose_name='Version note'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='description',
            field=models.TextField(blank=True, default='', help_text="short description what's part of this Product List", max_length=4096, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
