# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 10:21
from __future__ import unicode_literals
import logging
from django.db import migrations, models
import django.db.models.deletion
from app.productdb.models import ProductMigrationOption


def update_foreign_keys_on_product_migrations(apps, schema_editor):
    for e in ProductMigrationOption.objects.all():
        try:
            e.save()

        except:
            logging.warning("cannot save Product \"%s\" with replacement Product ID \"%s\", reset replacement product "
                            "ID" % (e.product.product_id, e.replacement_product_id))
            e.replacement_product_id = ""
            e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0018_auto_20161031_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmigrationoption',
            name='replacement_db_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_db_product', to='productdb.Product'),
        ),
        migrations.RunPython(update_foreign_keys_on_product_migrations)
    ]
