# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0022_auto_20161128_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='choose_migration_source',
            field=models.BooleanField(default=False, help_text='change the Migration Source for a Product Check (use not the preferred migration path)', verbose_name='choose Migration Source in Product Check'),
        ),
    ]
