# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0024_auto_20161227_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcheck',
            name='input_product_ids',
            field=models.CharField(help_text='unordered Product IDs, separated by line breaks or semicolon', max_length=65536, verbose_name='Product ID list'),
        ),
    ]
