# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0026_auto_20170115_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfile',
            name='file',
            field=models.FileField(upload_to='../data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_timestamp',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, help_text='last changes to the product data', verbose_name='update timestamp'),
        ),
    ]
