# -*- coding: utf-8 -*-
# Generated by Django 1.11.10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0027_auto_20170302_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eol_reference_url',
            field=models.URLField(blank=True, help_text='URL to the Product bulletin or EoL reference', max_length=1024, null=True, verbose_name='EoL reference URL'),
        ),
    ]
