# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0030_auto_20190716_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Unique Product ID/Number', max_length=512),
        ),
    ]
