# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-23 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0031_auto_20191123_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('product_id', 'vendor')]),
        ),
    ]
