# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0032_auto_20191123_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='vendor for the product list (only products from a single vendor can be used within a product list)', null=True, on_delete=django.db.models.deletion.CASCADE, to='productdb.Vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Product ID/Number', max_length=512),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='string_product_list',
            field=models.TextField(help_text='Product IDs separated by word wrap or semicolon', max_length=16384, verbose_name='Unstructured Product IDs separated by line break'),
        ),
    ]
