# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0033_auto_20200507_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='vendor',
            field=models.ForeignKey(help_text='vendor for the product list (only products from a single vendor can be used within a product list)', null=True, on_delete=django.db.models.deletion.CASCADE, to='productdb.Vendor', verbose_name='Vendor'),
        ),
    ]
