# Generated by Django 2.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0034_auto_20200526_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='string_product_list',
            field=models.TextField(help_text='Product IDs separated by word wrap or semicolon', verbose_name='Unstructured Product IDs separated by line break'),
        ),
    ]
