Vagrant.configure(2) do |config|
  config.vm.define "productdb", primary: true do |productdb|
    productdb.vm.box = "ubuntu/xenial64"

    productdb.vm.network "forwarded_port", guest: 80, host: 16000
    productdb.vm.synced_folder ".", "/vagrant", disabled: false

    # name is used in the ansible inventory which is generated by vagrant
    productdb.vm.define "productdb" do |productdb|
    end

    productdb.vm.provider "virtualbox" do |vb|
      vb.name = "productdb"
      vb.memory = "1024"
    end

    # install python (required for ansible)
    productdb.vm.provision "shell", inline: "sudo apt-get install python -y"

    productdb.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy/deploy-vagrant-file.yaml"
    end

    productdb.vm.post_up_message = "access the product database at http://localhost:16000"
  end
end
