Vagrant.configure(2) do |config|
  config.vm.define "productdb", primary: true do |productdb|
    productdb.vm.box = "ubuntu/xenial64"

    productdb.vm.network "forwarded_port", guest: 443, host: 16443
    productdb.vm.synced_folder ".", "/vagrant", disabled: false

    # name is used in the ansible inventory which is generated by vagrant
    productdb.vm.define "productdb" do |productdb|
    end

    productdb.vm.provider "virtualbox" do |vb|
      vb.name = "productdb"
      vb.memory = "1024"
    end

    # install python (required for ansible)
    productdb.vm.provision "shell", inline: "sudo apt-get install python -y -f"

    productdb.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy/stage_vagrant/deploy-vagrant-file.yaml"
    end

    productdb.vm.post_up_message = "access the product database at https://localhost:16443 (Ubuntu)"
  end
  config.vm.define "productdb_ldap" do |productdb_ldap|
    productdb_ldap.vm.box = "ubuntu/xenial64"

    productdb_ldap.vm.network "forwarded_port", guest: 443, host: 17443
    productdb_ldap.vm.synced_folder ".", "/vagrant", disabled: false

    # name is used in the ansible inventory which is generated by vagrant
    productdb_ldap.vm.define "productdb_ldap" do |productdb_ldap|
    end

    productdb_ldap.vm.provider "virtualbox" do |vb|
      vb.name = "productdb_ldap"
      vb.memory = "1024"
    end

    # install python (required for ansible)
    productdb_ldap.vm.provision "shell", inline: "sudo apt-get install python -y -f"

    productdb_ldap.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy/stage_vagrant/deploy-vagrant_with_ldap-file.yaml"
    end

    productdb_ldap.vm.post_up_message = "access the product database at https://localhost:17443 (Ubuntu with LDAP)"
  end
end
