Vagrant.configure(2) do |config|
  config.vm.define "productdb_dev" do |productdb_dev|
    productdb_dev.vm.box = "ubuntu/trusty64"
    productdb_dev.vm.host_name = "productdb-dev"

    productdb_dev.vm.network "forwarded_port", guest: 80, host: 15000
    #productdb_dev.vm.network "public_network"

    # name is used in the ansible inventory which is generated by vagrant
    productdb_dev.vm.define "productdb_dev" do |productdb_dev|
    end

    productdb_dev.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    productdb_dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "build-scripts/vagrant-development-provision.yaml"
    end

    productdb_dev.vm.post_up_message = "access the vagrant machine at http://localhost:15000"
  end

  config.vm.define "productdb", primary: true do |productdb|
    productdb.vm.box = "ubuntu/trusty64"
    productdb.vm.host_name = "productdb"

    productdb.vm.network "forwarded_port", guest: 80, host: 16000

    # name is used in the ansible inventory which is generated by vagrant
    productdb.vm.define "productdb" do |productdb|
    end

    productdb.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    productdb.vm.provision "ansible" do |ansible|
      ansible.playbook = "build-scripts/vagrant-production-provision.yaml"
    end

    productdb.vm.post_up_message = "access the vagrant machine at http://localhost:16000"
  end
end
