FROM productdb/basebox:latest

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SECRET_KEY PlsChgMe
ENV DJANGO_LOG_LEVEL info
ENV POSTGRES_DB productdb
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD plschgme
ENV PDB_DATABASE_HOST database
ENV PDB_DATABASE_PORT 5432
ENV PDB_REDIS_HOST redis
ENV PDB_REDIS_PORT 6379

COPY . /var/www/productdb/source

WORKDIR /var/www/productdb/source

CMD python3 manage.py celerycam --loglevel=${DJANGO_LOG_LEVEL}
