FROM productdb/basebox:latest

ENV PDB_GUNICORN_WORKER 3

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SECRET_KEY PlsChgMe
ENV DJANGO_LOG_LEVEL info
ENV POSTGRES_DB productdb
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD plschgme
ENV PDB_DATABASE_HOST database
ENV PDB_DATABASE_PORT 5432
ENV PDB_REDIS_HOST redis
ENV PDB_REDIS_PORT 6379

ADD . /var/www/productdb/source

WORKDIR /var/www/productdb/source

EXPOSE 8000

CMD gunicorn django_project.wsgi:application --bind 0.0.0.0:8000 \
        --workers ${PDB_GUNICORN_WORKER} \
        --log-level=${DJANGO_LOG_LEVEL} \
        --limit-request-line 6144 \
        --timeout 600 \
        --access-logfile=-
