FROM nginx:stable

RUN apt-get update && \
    apt-get install -y python3

ENV PDB_GUNICORN_WORKER 3

ADD ./deploy/docker/nginx /etc/nginx/template

EXPOSE 443
EXPOSE 80

CMD python3 /etc/nginx/template/update_nginx_config.py && nginx -g "daemon off;"
