FROM productdb/basebox:latest

ENV PDB_CELERY_CONCURRENCY 4

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SECRET_KEY PlsChgMe
ENV DJANGO_LOG_LEVEL info
ENV POSTGRES_DB productdb
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD plschgme
ENV PDB_DATABASE_HOST database
ENV PDB_DATABASE_PORT 5432
ENV PDB_REDIS_HOST redis
ENV PDB_REDIS_PORT 6379

ADD . /var/www/productdb/source

WORKDIR /var/www/productdb/source

CMD celery beat -A django_project \
        --loglevel=${DJANGO_LOG_LEVEL}
