from tests.functional.api.test_api_interaction import *
from tests.functional.api.test_swagger_interface import *
from tests.functional.user_interface.test_login_and_user_settings import *
from tests.functional.user_interface.test_views import *
from tests.functional.user_interface.test_bulk_eol_check import *
from tests.functional.user_interface.test_cisco_api_settings_view import *
from tests.functional.user_interface.test_import_products import *
from tests.functional.user_interface.test_settings_permissions import *
from tests.functional.user_interface.test_sync_local_db_with_cisco_api import *
