"""
Definition of the API endpoints for the unit tests
"""
from django.core.urlresolvers import reverse

PRODUCT_API_ENDPOINT = reverse("productdb:products-list")
PRODUCT_DETAIL_API_ENDPOINT = PRODUCT_API_ENDPOINT + "%i/"
PRODUCT_DETAIL_META_API_ENDPOINT = PRODUCT_API_ENDPOINT + "%i/meta/"
PRODUCT_BY_NAME_API_ENDPOINT = PRODUCT_API_ENDPOINT + "byname/"
PRODUCT_COUNT_API_ENDPOINT = PRODUCT_API_ENDPOINT + "count/"

PRODUCT_LIST_API_ENDPOINT = reverse("productdb:productlists-list")
PRODUCT_LIST_DETAIL_API_ENDPOINT = PRODUCT_LIST_API_ENDPOINT + "%i/"
PRODUCT_LIST_DETAIL_NAMED_PRODUCTS_API_ENDPOINT = PRODUCT_LIST_API_ENDPOINT + "%i/namedproducts/"
PRODUCT_LIST_GET_PRODUCTS_DATA_API_ENDPOINT = PRODUCT_LIST_API_ENDPOINT + "%i/products_data/"
PRODUCT_LIST_BY_NAME_API_ENDPOINT = PRODUCT_LIST_API_ENDPOINT + "byname/"
PRODUCT_LIST_COUNT_API_ENDPOINT = PRODUCT_LIST_API_ENDPOINT + "count/"

VENDOR_API_ENDPOINT = reverse("productdb:vendors-list")
VENDOR_DETAIL_API_ENDPOINT = VENDOR_API_ENDPOINT + "%i/"
VENDOR_PRODUCTS_DATA_API_ENDPOINT = VENDOR_API_ENDPOINT + "%i/products_data/"
VENDOR_BY_NAME_API_ENDPOINT = VENDOR_API_ENDPOINT + "byname/"
