# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('type', models.CharField(choices=[('INFO', 'info'), ('SUCC', 'success'), ('ERR', 'error'), ('WARN', 'warning')], default='INFO', max_length=8)),
                ('summary_message', models.TextField(max_length=16384)),
                ('detailed_message', models.TextField(max_length=16384)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
