# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the Text Block (predefined)', max_length=512, unique=True, verbose_name='Name')),
                ('html_content', models.TextField(help_text='content of the text block (HTML possible)', max_length=16384, verbose_name='HTML content')),
            ],
        ),
    ]
