# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_textblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='html_content',
            field=models.TextField(blank=True, help_text='content of the text block (HTML possible)', max_length=16384, null=True, verbose_name='HTML content'),
        ),
    ]
